/**
 * Migration rollback generator.
 *
 * Given a forward migration, generates the reverse DDL to undo it.
 * Handles:
 * - CREATE TABLE → DROP TABLE
 * - ADD COLUMN → DROP COLUMN (ALTER TABLE ... DROP COLUMN)
 * - CREATE INDEX → DROP INDEX
 * - DROP TABLE → warns (cannot reverse without backup)
 * - DROP COLUMN → warns (data is lost)
 * - ADD CONSTRAINT → DROP CONSTRAINT
 * - MODIFY COLUMN → warns (original type unknown without schema)
 * - RENAME → reverse RENAME
 */

import type { DDLStatement, ParsedMigration } from "../parsers/flyway-sql.js";

export interface RollbackStatement {
  forward: string;
  rollback: string;
  isReversible: boolean;
  warning: string | null;
}

export interface RollbackReport {
  statements: RollbackStatement[];
  fullyReversible: boolean;
  warnings: string[];
  rollbackSql: string;
}

export function generateRollback(migration: ParsedMigration): RollbackReport {
  const rollbackStatements: RollbackStatement[] = [];
  const warnings: string[] = [];

  // Process in reverse order (last statement rolled back first)
  for (let i = migration.statements.length - 1; i >= 0; i--) {
    const stmt = migration.statements[i];
    const result = generateRollbackStatement(stmt);
    rollbackStatements.push(result);
    if (result.warning) {
      warnings.push(result.warning);
    }
  }

  const fullyReversible = rollbackStatements.every(s => s.isReversible);

  // Build the rollback SQL
  const rollbackLines: string[] = [];
  rollbackLines.push("-- Rollback migration: " + migration.filename);
  if (migration.version) {
    rollbackLines.push("-- Reverses version: " + migration.version);
  }
  rollbackLines.push("-- Generated by MCP Migration Advisor");
  rollbackLines.push("");

  if (!fullyReversible) {
    rollbackLines.push("-- WARNING: This migration is NOT fully reversible.");
    rollbackLines.push("-- Some operations require manual intervention (see warnings below).");
    rollbackLines.push("");
  }

  for (const stmt of rollbackStatements) {
    if (stmt.warning) {
      rollbackLines.push(`-- WARNING: ${stmt.warning}`);
    }
    rollbackLines.push(stmt.rollback + ";");
    rollbackLines.push("");
  }

  // Add Flyway schema_version cleanup
  if (migration.version) {
    rollbackLines.push("-- Remove migration record from Flyway history:");
    rollbackLines.push(`DELETE FROM flyway_schema_history WHERE version = '${migration.version}';`);
  }

  return {
    statements: rollbackStatements,
    fullyReversible,
    warnings,
    rollbackSql: rollbackLines.join("\n"),
  };
}

function generateRollbackStatement(stmt: DDLStatement): RollbackStatement {
  switch (stmt.type) {
    case "CREATE_TABLE":
      return {
        forward: stmt.raw,
        rollback: `DROP TABLE IF EXISTS ${stmt.tableName}`,
        isReversible: true,
        warning: null,
      };

    case "DROP_TABLE": {
      const hasCascade = stmt.details.cascade === "true";
      return {
        forward: stmt.raw,
        rollback: `-- Cannot reverse DROP TABLE ${stmt.tableName} without schema backup`,
        isReversible: false,
        warning: hasCascade
          ? `DROP TABLE ${stmt.tableName} CASCADE is irreversible — table and all dependent objects (views, foreign keys, indexes) are permanently destroyed. Each dependent object must be recreated manually.`
          : `DROP TABLE ${stmt.tableName} is irreversible — table structure and data are lost. Restore from backup.`,
      };
    }

    case "CREATE_INDEX": {
      // Extract index name from the raw SQL
      const indexMatch = stmt.raw.match(/INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?(?:`|"|)?(\w+)/i);
      const indexName = indexMatch ? indexMatch[1] : "unknown_index";
      const concurrently = stmt.details.concurrently ? "CONCURRENTLY " : "";
      return {
        forward: stmt.raw,
        rollback: `DROP INDEX ${concurrently}IF EXISTS ${indexName}`,
        isReversible: true,
        warning: null,
      };
    }

    case "DROP_INDEX": {
      return {
        forward: stmt.raw,
        rollback: `-- Cannot reverse DROP INDEX without original index definition`,
        isReversible: false,
        warning: "DROP INDEX is irreversible without the original CREATE INDEX statement.",
      };
    }

    case "ADD_COLUMN":
      return {
        forward: stmt.raw,
        rollback: `ALTER TABLE ${stmt.tableName} DROP COLUMN IF EXISTS ${stmt.columnName}`,
        isReversible: true,
        warning: null,
      };

    case "DROP_COLUMN":
      return {
        forward: stmt.raw,
        rollback: `-- Cannot reverse DROP COLUMN ${stmt.columnName} on ${stmt.tableName} — data is lost`,
        isReversible: false,
        warning: `DROP COLUMN ${stmt.tableName}.${stmt.columnName} is irreversible — column data is lost. Restore from backup.`,
      };

    case "MODIFY_COLUMN": {
      if (stmt.details.setNotNull === "true") {
        return {
          forward: stmt.raw,
          rollback: `ALTER TABLE ${stmt.tableName} ALTER COLUMN ${stmt.columnName} DROP NOT NULL`,
          isReversible: true,
          warning: null,
        };
      }
      if (stmt.details.dropNotNull === "true") {
        return {
          forward: stmt.raw,
          rollback: `ALTER TABLE ${stmt.tableName} ALTER COLUMN ${stmt.columnName} SET NOT NULL`,
          isReversible: true,
          warning: "Reversing DROP NOT NULL requires all existing values to be non-null.",
        };
      }
      if (stmt.details.typeChange === "true") {
        return {
          forward: stmt.raw,
          rollback: `-- Cannot reverse type change on ${stmt.tableName}.${stmt.columnName} — original type unknown`,
          isReversible: false,
          warning: `Type change on ${stmt.tableName}.${stmt.columnName} requires knowing the original type. Check schema before migration.`,
        };
      }
      if (stmt.details.setDefault === "true") {
        return {
          forward: stmt.raw,
          rollback: `ALTER TABLE ${stmt.tableName} ALTER COLUMN ${stmt.columnName} DROP DEFAULT`,
          isReversible: true,
          warning: null,
        };
      }
      if (stmt.details.dropDefault === "true") {
        return {
          forward: stmt.raw,
          rollback: `-- Cannot reverse DROP DEFAULT on ${stmt.tableName}.${stmt.columnName} — original default value unknown`,
          isReversible: false,
          warning: `DROP DEFAULT on ${stmt.tableName}.${stmt.columnName} requires knowing the original default value to reverse.`,
        };
      }
      return {
        forward: stmt.raw,
        rollback: `-- Cannot reverse: ${stmt.raw.slice(0, 80)}`,
        isReversible: false,
        warning: `Column modification on ${stmt.tableName}.${stmt.columnName} may not be reversible.`,
      };
    }

    case "ADD_CONSTRAINT":
      return {
        forward: stmt.raw,
        rollback: `ALTER TABLE ${stmt.tableName} DROP CONSTRAINT IF EXISTS ${stmt.details.constraintName || "unknown_constraint"}`,
        isReversible: true,
        warning: null,
      };

    case "DROP_CONSTRAINT":
      return {
        forward: stmt.raw,
        rollback: `-- Cannot reverse DROP CONSTRAINT ${stmt.details.constraintName} — original definition unknown`,
        isReversible: false,
        warning: `DROP CONSTRAINT ${stmt.details.constraintName} is irreversible without the original constraint definition.`,
      };

    case "RENAME": {
      // Try to extract old and new names from the raw SQL
      const renameMatch = stmt.raw.match(/RENAME\s+(?:TO|COLUMN\s+\w+\s+TO)\s+(?:`|"|)?(\w+)/i);
      if (renameMatch && stmt.tableName) {
        const newName = renameMatch[1];
        if (stmt.raw.toUpperCase().includes("RENAME COLUMN")) {
          const colMatch = stmt.raw.match(/RENAME\s+COLUMN\s+(?:`|"|)?(\w+)(?:`|")?\s+TO\s+(?:`|"|)?(\w+)/i);
          if (colMatch) {
            return {
              forward: stmt.raw,
              rollback: `ALTER TABLE ${stmt.tableName} RENAME COLUMN ${colMatch[2]} TO ${colMatch[1]}`,
              isReversible: true,
              warning: null,
            };
          }
        }
        return {
          forward: stmt.raw,
          rollback: `ALTER TABLE ${newName} RENAME TO ${stmt.tableName}`,
          isReversible: true,
          warning: null,
        };
      }
      return {
        forward: stmt.raw,
        rollback: `-- Cannot parse RENAME for rollback: ${stmt.raw.slice(0, 80)}`,
        isReversible: false,
        warning: "RENAME could not be parsed for automatic rollback.",
      };
    }

    case "ALTER_TABLE":
    case "OTHER":
    default:
      return {
        forward: stmt.raw,
        rollback: `-- Manual rollback needed: ${stmt.raw.slice(0, 80)}`,
        isReversible: false,
        warning: `Statement requires manual rollback: ${stmt.raw.slice(0, 80)}`,
      };
  }
}
